name: Node.js CI

on:
    push
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.yml'

jobs:
  build:

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile
    - run: npm run package
    - run: npm run lint
      env:
        CI: true
  
